backend:
  name: github
  repo: kungfukoala/_underscore # Replace with your repo
  branch: master

media_folder: "src/img/gallery" # Folder where user uploaded files should go
public_folder: "img/gallery"
